"""Add gstins column to buyers

Revision ID: 22b457ad3188
Revises: a26b918fe805
Create Date: 2026-05-01 14:54:59.022438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b457ad3188'
down_revision: Union[str, None] = 'a26b918fe805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('gstins', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyers', 'gstins')
    # ### end Alembic commands ###
